language: node_js
sudo: false
node_js:
- '4'
branches:
  only:
  - master
  - /^v\d+(\.\d+)*$/
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - libstdc++6
script:
- git clone https://github.com/Rapid-Imaging-Tech/gl-style-package-spec.git
- cd gl-style-package-spec
- bash ./task/run.sh

env:
  global:
    - secure: "OgHk6OesHQGkSOOII1pd2KO9hU/qTKv2Re3YPrpNmaCXcaT+pqOdVyla2T+ib5OhOwfWh+BoiQ1skYo51mIiDM1FsTepsK8FGE89T9e389RAgHjBbXn964LK7a1yvT0MUz9LmRlVcnkD1NwwroKDB/2qzZWTQlLULp/Fdvq9fFD9IDjIMfoAdoN1O3+Q3uFEA6LC38yg6izQvSMAtNsqNFoit7NgGKccrHAO4ZrQxfI70rUVqdv3f+GBc+OgI257mSI+k6gebdELX8F9B3bDFzzfU9S07rqJgB218X8AnUAp9Pv2RmjXh29uI8UFsdtsVFa4yz7EmM/M1iu+d9qvUL9ESUOoT/DGLiQJkeTDMw/KKJPnGM8xiOO7te99Vy3MDfuVmGco3XSMI9fJTIQo+AE5e5Kr8g8pv4M00ybXY5umlGl7hZdd6Rywst7gSLcia0iiMVGuUOL/tLqgI5yskSP/H7hYM8M6qOl3PuOUjijhEUJA5+hFQBJ231vVDpdzHuROLhN1wZcRZo+1ubsFnO1I4qL5yd5pXXCr+gSjwntCYpF8uzlCGB4GIpDwAWbejCpbIjbHWT5avlaro3YiFAXk8ygQGYF4aF6z3KVM9bNXzNxHMWQGRNU51q3AKwqcWYElwqN7HIbrk+dC411V5Cedr+LWKzn4qT1DAoQt+lU="
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: build/${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
