language: node_js
sudo: false
node_js:
- '4'
branches:
  only:
  - master
  - /^v\d+(\.\d+)*$/
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - libstdc++6
script:
- git clone https://github.com/bit-chemist/gl-style-package-spec.git
- cd gl-style-package-spec
- bash ./task/run.sh

env:
  global:
    - secure: "JC5DLBaZAXwFZR+hVLacQZCgQhFxEFkMq3MA8mzanS2SxAhgAysVmWuoTQ05u1p7cx/nUb5pIS+En2HFGNvV7oDLcDfNHMQvrqZq1tTjytI1a4G9/rIRIWUrPDImgk3FIjnhVIeTML7C32pXM+wFhvi7m3In9v7jTDe09GJNZrrLDyUkJS7wDdLSxjcueCAZojGcHWiKirBqtN7fNpTMlvMoHuqShTJDqM3uHE/TiZHJLieGZ6FP8724FDt8GoqCnqTw3kD49YYVSRyV/8U85gzm4jWWcSr/WyRv8vZnxKkDa6h7eNUSqZlH+YoFCa6SbqSMOvd6b5mFrjsBw6k+Mrwgjefo8GN7x4JGbqt2+PEIB5wQrf6+F/9ua0B7MwaVECgmNJcVx92uo7ud4LP+NT01PX8lGdG7kIAOqQN5E1CBckImOD8jKn94cEVkZUvvf37Bc7rmrIiEXPVwbLC7fWd4VuqMmfZR2mexQB+mf2hX+R2nbTHThG+fMC5LkoMrT7VsnB4rKzJxlt5H3jOGEjoi+bMPTSqt5lSVO8Z3I8xdeT2+Sj8lfcLjgZUDVhN03S3sijuj+fx9bVxBBswLFmx63TDO7imEUNQaaw29IuoGPC+B4dmGV2szV2T5EanLJ5MdueirAQeUHin7cW/10abrOXXbuSIrnKCNfw9izT4="
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: build/${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
